### ISSUE TITLE
GPS tracking issues 

### ISSUE THREAD

**Issue by Ryan61065** [lrmapp/issues#11]
The program isn't sending data to the server I guess. Any ideas

**Comment by Ryan61065** [comment]
says im connected but wont log anything in the logbooks or track my flight

**Comment by Ryan61065** [comment]
says im connected but wont log anything in the logbooks or track my flight

**Comment by optoisolated** [comment]
Can confirm this happens to me as well. I get the flight log in FSHub with the map, but no live data.

**Comment by cybertsotsi** [comment]
This is happening to me, all features except GPS tracker is working, flights are logged and I can see my plane on the radar but nothing on the GPS.

**Comment by allebb** [comment]
I can confirm that this is now fully fixed and working - I've made and tested updates this morning.

The issue was caused by some API changes made last year by Google to the Maps API which I've had to reflect in the main FSHub codebase.

Apologies for the delay in getting this fixed up, I've had to prioritse other things and being the only developer, it makes it hard to prioritise this over other things.

FYI - There is no need to update your LRM client software or anything, simply refresh (to clear any cache) on the GPS page on the FSHub website (if it doesn't immediately work anyway).

Kind regards,
Bobby
