### ISSUE TITLE
LRM opes then auto shuts the application but it still works in FSX:SE and says "LRM is open"

### ISSUE THREAD

**Issue by AusPilot11** [lrmapp/issues#12]

**Comment by allebb** [comment]
Hi @AusPilot11 , Sorry for the delay in getting around to looking at this for you.

Are you running LRM in "BlackBox mode"? - If you are, the LRM icon will be running in the system tray, you'll need to double click it to open the application (or right-click for additional options).

Please could you also confirm if, when you land you get the landing details to appear inside the simulator? - I believe this may be caused by you simply running the application in BlackBox mode but this test will confirm either way.

If you want to disable "BlackBox mode" you can do that from the setting of the LRM client - more details can be found in the user manual here: https://lrmclient.org/docs/LRM-Client-Documentation_v4.0.0.pdf

I hope this helps.

**Comment by allebb** [comment]
Closing issue due to no response from user. Feel free to re-open if this is still an issue and my notes above did not help 👍
