### ISSUE TITLE
Aircraft Manager - Tail Number issue

### ISSUE THREAD

**Issue by DenUnion** [lrmapp/issues#19]
Some aircraft have registration number longer
than 6 symbols (for example XX-XXXXX instead
of casual XX-XXX) but in LRM aircraft manager
section you can type in 6 symbols only. It'd be
awesome if characters limit on Tail number
section could be extended.

**Comment by allebb** [comment]
Hi @DenUnion,

I can confirm that I have made the changes to FsHub this evening to enable this feature/change BUT in addition to the FsHub changes, it will also require a new release of the LRM client to complete this feature request.

At the moment there are a few other changes that are currently in private beta testing but once these other changes are reported at working without issues, the new LRM client will be released which will then enable you to use 7 characters instead of the current limit of 6.

Hope this helps 👍

**Comment by allebb** [comment]
Hi @DenUnion I can confirm that LRM 5.5.1 has been released this afternoon which includes the ability to use tail numbers up to a maximum of 8 characters now.

Feel free to download the latest version of the client from our website 👍 

I will now close this issue as no further actions (dev wise) are required.
