### ISSUE TITLE
LRM gets error on startup and wont run, regardless if fsx is running or not 

### ISSUE THREAD

**Issue by harry8227** [lrmapp/issues#2]
LMR gets error on startup and wont run, regardless if fsx is running or not

**Comment by allebb** [comment]
Any chance you could post up the error message/a screenshot of the error?

What version of Windows are you running too?

Cheers,
Bobby

**Comment by vortekc** [comment]
I have similar problem. In the windows log i found this:
Application: LRM.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
   at System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   at System.Number.ParseDecimal(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   at System.Convert.ToDecimal(System.String)
   at LRM.WebServices.isNewVersionAvailable()
   at LRM.MainForm.autoCheckUpdates()
   at LRM.MainForm..ctor()
   at LRM.Program.Main()

P.S. i am fix this by changing date and numbers format to English (US)
Turn off update check in LRM.exe.config config file help too

**Comment by gaabne** [comment]
I have the same error - using Windows 7 64 - with French regionals!
When I set English (US) it works, but it cannot be a permanent solution ! 

Could you consider to allow for other regional setting - it would be great.
Thank you for this nice utility.

**Comment by allebb** [comment]
Hey guys - Thanks for the additional reports, I'll look to get this resolved and a new version pushed ASAP.

**Comment by gaabne** [comment]
Hello,
I just discovered that the failure on non english systems is linked to the ckeck for update option.
Turn off update check option (as well as upload landing rate) solves the issue.

I like a lot your application - I am just missing the Ground Speed at same time to help me improve my landings...

Thanks to consider that option.

**Comment by allebb** [comment]
Evening all  - Been really busy recently so I'm glad that you've been able to find a temporary work around.

Just a quick note to let you know that this will be fixed in the 2.4 release that I wil lbe releasing tomorrow.

Thanks for your patience :+1:

**Comment by gaabne** [comment]
Thank you for your note.

Would you mind, taking opportinity of this update, to add an option to display the speed at landing time ?
I known it was displayed in a previous version, but some people asked to suppress it  :(
Cheers
Gérard

**Comment by allebb** [comment]
Yeah sure thing - Would you mind openig a separate  issue  (well, feature request)  on GitHub for this request and I will work on getting that added this evening too.

I assume you mean have it displayed on the desktop app too (instead of on the green in-sim ticker?)

I'd be more than happy to add it to the desktop app display but not keen on adding it to the flight sim ticker really especially as people didn't like too much info displayed in-sim.

Cheers,
Bobby

**Comment by allebb** [comment]
On the other hand @gaabne ... I could, if you did want it on the green, in-sim ticker, I suppose I could add an option to the LRM tool to "Display additional stats in-sim" which could then show the IAS at landing, wind speed etc. - Just open the the other "Feature request" with your requirements and I will look to get it added this evening.

**Comment by allebb** [comment]
This has now been fixed and tested. The latest v2.4 release can be downloaded and installed from: http://lk2.in/fw

Please report back any issues but all should work fine regardless of your regional settings!

**Comment by allebb** [comment]
@gaabne I just wondered if you have had a chance to test this as yet and if so, could you confirm it's all ok for you now?

**Comment by gaabne** [comment]
@bobsta63 
I made a quick test - everything is ok for me :)
A **big big** thanks

Gérard

**Comment by allebb** [comment]
That's great - Thanks for confirming and you are very welcome :+1:
