### ISSUE TITLE
Can´t  acces lrmlive.com

### ISSUE THREAD

**Issue by Labox0811** [lrmapp/issues#5]
As the title says, I can´t acces the sit. No matter what browser I use, I always get the following message:

This server could not prove that it is lrmlive.com; its security certificate is from celsporta.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

Is this something on my end?

Best, Arne

**Comment by allebb** [comment]
Hi @Labox0811 

The server is down at the moment due to cost - It's heavily used and the bandwidth is killing me (money wise) - At the moment I'm looking for a cheaper VPS to host it on/push for some hosting donations.

Hopefully I will have it back and online soon - I've got all of the data and files backed up (so don't worry, nothing is lost) and in the mean time you can continue to use the client to track landing rates - once the site is back online your flight data will be added again to your pilot profile.

Hope this helps explain what's going on etc.,

Cheers,
Bobby.

**Comment by allebb** [comment]
The site is now back online, closing this issue as it is no longer applicable.
