### ISSUE TITLE
LRMLIVE

### ISSUE THREAD

**Issue by ghost** [lrmapp/issues#6]
Hi,
I have a problem with lrmlive.com. Whenever i load it up, it says connection timed out. I have tried firewall but nothing seems to work.

From, Will

**Comment by allebb** [comment]
Hi Will,

The main LRMLive site has been down recently due to hosting requirements and costs - the service was widely used by users of the tool and server was getting hammered... I'll shortly be doing an overhaul of the site and further optimising and configuring a new load-balanced environment to help better cope with the traffic and global usage of the site.

The new version of the site will be fully operational before November and all existing clients will automatically reconnect as expected.

Cheers,
Bobby

**Comment by allebb** [comment]
LRMLive is now back online, further optimisation is being done but the site is usable and tracking flights again.

All existing pilot accounts, image uploads and flight logs have been restored. - Further changes will be made and deployed to the site over the upcoming weeks.
