### ISSUE TITLE
Categorise and output the landing eg. "good, bad, excellent"

### ISSUE THREAD

**Issue by jmhelms** [lrmapp/issues#7]
I also use X-Plane and it has a program like
yours...that program "rates" your landing 
such a good, acceptable, hard, "Anyone 
Survive?, " etc.

I see your statistics, but not sure I can make 
much common sense of them...

Appreciate your consideration of this request..

John Helms, Houston, TX

**Comment by allebb** [comment]
Hi John,

I sure can add something like that... Did you have any recommendations on the FPM "limits" to define/calculate the lanidng? Something along these lines maybe? - Feel free to let me know if I'm way off the mark on any of these/recommend other rating text messages...

| Lower limit (FPM)        | Upper limit (FPM)          | Rating text  |
| ------------- |:-------------:| -----:|
| 0     | 90 | Great |
| 90      | 200      |   Good |
| 200 | 400      |    Acceptable |
| 400 | 500      |    Bad |
| 500 | 700      | Dangerous |
| 700 | > 700 | Fatal |

**Comment by allebb** [comment]
Whoops, my bad, didn't mean to close this...

**Comment by jmhelms** [comment]
Hi Bobby...to be honest, I don't
much about landing rates...but the
above look good to me...

Would they be the same for all
aircraft, such as commercial air
liners?....that was a minor
problem in the XP app...

I wanted to make a small donation
but the "donate" link did not work..
error message said something about
taking too long to load page...

Cheers, John H.

**Comment by allebb** [comment]
Hi John,

Sorry for the late reply, I've been giving this some thought (as, like you I'm not sure if this would be valid for ALL aircraft but I know that my example is pretty close for commercial aircraft eg. Airbus A320 etc.)...

Anyway, my plan is to offer a 'default' set of limits (as per my above examples) but will also allow people to upload their own aircraft specific ones too (simply drop in a folder) and if the aircraft name matches the config file name then it'll use those parameters for outputting the landing "result".

Will be starting work on this, this week 👍 and also the new version of the LRM statistics/flight report site :)

With regards to the donation - If you wanted to donate (don't feel obliged to though) you could always send me a donation to my PayPal account: bobbyallen.uk@gmail.com which would be much appreciated :)

Cheers,
Bobby

**Comment by allebb** [comment]
...I'll also add a section to the main LRM client site where users could "share" their configurations for certain aircraft types - may make things easier and get the community "sharing" their own configuration/research on landing rate limits for certain aircraft.

**Comment by jmhelms** [comment]
Hi Bobby..thank for the reply...know
you are busy...

I will send a small donation...I know
you are busy...

Your solution sounds great...

Is there any way to be notified of the
new version of LRM...does it check for
updates?

Cheers, John H.

**Comment by jmhelms** [comment]
This sounds great as well...BTY I think
, upon reflection, your initial rates are
,as we say here: "good enough for
government work"

Cheers, John H.

**Comment by allebb** [comment]
Hey John,

First of all, many thanks for the kind donation 👍 

With regards to the new version notification - Yes, the LRM client (unless you've disabled it in the menus' will automatically check and notify you if there is a new version available.

Will do my best to get the new version of the client completed and released before the end of next week :)

Speak soon and would really appreciate if you could give me feedback on the new feature once it's been released - I'll also update this issue too once it's released so that you can download and install the latest version (just incase you've disabled the 'Check for updates' option :))

**Comment by jmhelms** [comment]
Hi Bobby...your'e welcome for the small donation..
least I could do for a very helpful utility...

No hurry from my end on the update and
happy to give feedback...

Sorry for this last minute idea....could the
app be a "popup" that just appears on screen
upon the landing in a small, movable box?...
box would stay for a minute or so and then
disappear?...sounds to me like a lot of trouble...
and if it is the just go with current idea...

Cheers, John H., Houston, TX, USA

**Comment by allebb** [comment]
Hi John,

Just to let you know that I've now started work on this, and so far my testing is going great :) - Hopefully be released midweek!

The LRM site is now back online too (in case you hadn't noticed) - You can re-login and look over your old flight logs and start logging those flights again etc!

Over the coming weeks, I'm adding massive amounts of improvements to that site too and giving it a facelift (making it look far better and new functionality).

Speak soon,
Bobby

**Comment by jmhelms** [comment]
Hi Bobby...thanks for writing...just
really busy here...

But did go to your site and register (or re register)
interested in the GPS tracking and will give it a
try...

Good luck on the new improvements...

John H., Houston, TX

**Comment by jmhelms** [comment]
Hi Bobby...how do I get the GPS feature
to work

Created an account...the LRM
program works and shows connection to
P3D...the website map shows me at KHOU
(Hobby, Houston)...but when i take off
from there, the website map does not follow my
flight...is it supposed to?

Cheers, John H.

**Comment by allebb** [comment]
Yes, it will track your flight as long as you have created and entered an API token into the client preferences window, see this page for instructions on how to do it :)

https://lrmlive.com/docs/client#lrmlive-account-integration

Hope this helps :)

Kind regards,
Bobby

**Comment by jmhelms** [comment]
Hi Bobby...thanks for the information...
got it all connected..is there a way to speed up
the refresh rate on the GPS map?....the position
tracking plane seems to jump from one spot to
another, instead to move smoothly...not all that big a deal...

Cheers, John H.

**Comment by allebb** [comment]
Hi John,

The GPS refresh rate is tied to how often the client sends your aircraft GPS coordinates back to the server... I'll see what other improvements I can do in the next release :)

**Comment by jmhelms** [comment]
Thanks....good luck

John H.

**Comment by allebb** [comment]
Hi John, This code has now been added and fully tested in the latest version of the client, the client will be released tomorrow evening (GMT) (just adding a few other features too :))

Keep an eye on the client as it'll soon prompt you to update to make use of the new functionality 👍

**Comment by jmhelms** [comment]
Thanks, Bobby...looking forward...

Happy Thanksgiving!

John H.

**Comment by allebb** [comment]
No problem :) - I hope you like the new look of the new LRMLive stats site that I released this week! 👍 

Happy Thanksgiving to you too!

Oh and btw... The new client is fully compatible with X-Plane too (in-case you was interested in using it for that too :))

**Comment by allebb** [comment]
Evening John!!

As promised the new LRM client has just been released, you can grab it from the LRM Client site (https://client.lrmlive.com) - I've not yet updated the "check client updates" API yet so clients won't yet prompt to download the latest version - I just want to make sure we're all totally "bug free" first.

I decided that instead of using words like "good", "great" etc. (as there seems to be a lot of ambiguity on the internet as to what is refereed to as a "good" or "great" landing but instead I categorised them with the rates as follows (I changed the ranges too based on what I had read pilots generally feel about landing rate categories):-

| Lower limit (FPM)        | Upper limit (FPM)          | Rating text  | Description |
| ------------- |:-------------:| :-----:|-------|
| 0     | 85 | Smooth | A greased and smooth landing that in wet conditions and short runways could not be the best |
| 86     | 209      |   Perfect | The best mix of smooth landing and contact/prevention of aqua-planning etc. | 
| 210 | 349      |    Firm | Great in certain circumstances (short runways, wet conditions)! |
| 350 | 399      |    Hard | Not damaging to the aircraft but getting that way - Passengers are probably a bit shaken though! |
| 400 | 549      | Concerning | Should probably get the landing gear checked out by engineers as it's probably breached the design landing rate limits |
| 550 | 799 | Dangerous | For various aircraft types this could be dangerous and the aircraft could start to break up |
| > 800 |  | Fatal | It can't be good... I assume, if you survive a landing at this rate you're pretty lucky! |

I've also added another really cool feature (which if you fly airliners you may like) - If you do a landing of less than -300fpm - You can enable the "Cabin Applause" setting in the preferences and you will hear a faint applause of the passengers :) - It's a pretty neat feature if I say so myself :)

Hope you manage to give it a test and hopefully let me know what you think 👍

**Comment by jmhelms** [comment]
Hi Bobby...thanks for the headsup...downloaded
the new meter and have made a couple of landings...

I want test some more...thanks for all your hard work...
the thing I'd like you to look at is the long time from
landing to result showing...sometimes seems like
30 seconds...a little long I think...hopefully something
can be done there...I heard several rounds of applause
even when I had not checked the box...minor stuff...

I will test more tomorrow and report...

In the meantime let me share a French site I just
stumbled upon...they have many cool P3D downloads
that fly well and come with sophisticated HUD's...some
are my favorite planes at the moment...give the MonoBi
package a try for sure...some good small helis...most
text in English...

http://frenchvfr.free.fr/index.php?lng=en


Cheers, John H.

**Comment by allebb** [comment]
Hi John,

Thanks so much for doing some testing for me, it was actually a massive help!!! I failed to find those two bugs (clapping playing regardless of if the user has enabled it and the refresh rate of landing states updating the form).

I can however advised that I've now fixed BOTH issues and have tested and all seems to be working perfect now!

I would **really** appreciate it if you could re-download the file again (I've updated it on the site now) and just re-run the installer and do a few final tests/re-test those issues before I publicly announce the new release.

Thanks for sharing that URL too... I'll check it out over the weekend :)

Hope to hear from you soon,

All the best,
Bobby

**Comment by jmhelms** [comment]
Hi Bobby....downloaded the new version...

Got in a couple of landings...

My comments...

The applause issue seems fixed...

The installer installed w/o giving my
  choice of a directory...I always like that...
    the installer did find my previous install...

I don't think the program found all my landings...
   was doing them pretty quick, like touch and goes...

I don't see any improvement in the refresh rate...

The "banner" on top of the sim page is really nice...
   well done on that...

For your "Dangerous" category of landing, what about
  "R.I.P."?...from my XPlane version...

You have to try the website I sent you...a little hard
, at first, to navigate around, but well worth it...my favorite
planes and heli are: MonoBi package; Push Marine;
Cessna (150) Open Alpha; and Heli UMN...you may find others...
enjoy...great HUD's that have selectable screens...

Cheers, John H.

**Comment by allebb** [comment]
Thanks for re-testing and your further feedback John :)

I have some answers for you....

With regards to the install path, that in theory is correct as you've you've upgraded over the top of your old version (and therefore the installer detected the current path) - If you had uninstalled and re-installed, it will prompt you for the path (as it didn't detect an older version on your PC) - Hope that makes sense?

With regards to capturing all landings - if these was very quickly take-offs and landings (takeoff and landing within 30 seconds, then no, it won't register due to to the logic I've added for preventing bounce registration, and prevents exploitation of the FSHub.io platform - I guess, this limit is not too much of an issue for most users.

I will do more testing on the Refresh rate issues tomorrow, all of my testing following my changes had been instant though :(

Could I just ask though, in regards to the Refresh rate - If you run the simulator in Windowed mode and have the client open next to it, when you land does the form show the landing rate instantly but just  doesn't appear in the simulator until several seconds later? - I assume this may be the case for you and I can therefore only assume that you must have rather low FPS? - Although I send the landing notification to the simulator instantaneously, it's the simulator that may lag in displaying the message (this is linked to FPS) - If you have the time to just try the above and let me know that would be really great, just to confirm that it is an FPS issue rather than a client issue?

So I assume you mean replace "Fatal" with "R.I.P"? :) - "Dangerous" is one before my "Fatal" rating - I think I'll keep it as "Fatal" (means the same thing I guess) but will add, in the next release an option to customise these names. "R.I.P" I personally feel is a little less professional than "Fatal" lol. - I do appreciate your feedback though and I will add in the ability to change the names in future.

Once again, your help is much appreciated :) - It would also be really interesting to know, if you tried running it in X-Plane too and whether of not you had an issue with the landing rate not appearing for several seconds?

**Comment by jmhelms** [comment]
Hi Bobby....my responses...

Understand about installer...no problemo...

With the 30 second limitation on each landing,
the program works great...almost instantaneous
reading on the program and in sim program...
you've got a winner now!...my FPS in 40's on
a gaming rig...a little old...

No biggie on "RIP"...I would now waste time
on making landing designations changeable...

When I mentioned XP  in a post, I was referring to
an XP specific landing program....but I tried yours
in XP 11 and it seems to work great (as above)...
amazing...well done...

Keep me appraised of what you are doing and
happy to beta test for you in future...

Where are you located?...

Cheers, John Helms, Houston, TX

**Comment by allebb** [comment]
Hi John, thank you so much for getting back to me again, I really thought that you may have had enough of the testing haha :)

That's really great to hear and I'm really pleased that all seems to work well in both sims 👍 

I will certainly keep you updated on progress when new features etc are released!

I'm located about 90 miles from London (in the UK) - So greetings to you and your family from England 👍

**Comment by jmhelms** [comment]
Hi Bobby...I think you've got a winner
on your hands....the XP version of your
the program is a "plugin"....barely know what
that means, except many people don't
like to have too many of them...so that should
be attractive re: how your program operates...
you should put it on the "X Plane Org" board...

Toured England many years ago in a van....was back in
London a couple of years ago and was lucky enough
to stay with friends in Richmond...so very beautiful...
London just amazing....would love to tour English
countryside again by car...only way to see a country...

Cheers, John H.
